version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "frontend"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "backend"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase
