# scratch file with example calls to db apis using VS Code plugin REST Client

GET http://localhost:4000/counselling-services

###
GET http://localhost:4000/counselling-services?school=ubc

###
GET http://localhost:4000/counselling-services?urgency=Immediate&delivery=App

###
GET http://localhost:4000/counselling-services?school=ubc&school=sfu

###
GET http://localhost:4000/counselling-services/622b940195fc76787d2782e2

###
POST http://localhost:4000/counselling-services
Content-Type: application/json

{
    "serviceName": "UBC Psychology Clinic",
    "school": "UBC",
    "organization": "UBC Psychology",
    "serviceType": [
        "Counselling"
    ],
    "urgency": "Same Month",
    "targetClients": [
        "Adults in Greater Vancouver"
    ],
    "isAllDay": false,
    "website": "https://clinic.psych.ubc.ca/services/",
    "specialty": [
        "Stress",
        "Anxiety",
        "Depression"
    ],
    "isOfferedOnline": false,
    "delivery": [
        "In Person"
    ],
    "description": "The UBC Psychology Clinic offers comprehensive psychological services adults. Our clinical services are provided by graduate students from UBC’s doctoral programme in clinical psychology. Student clinicians are closely supervised by Registered Psychologists from our faculty and the community.Our Clinic is not able to provide psychiatric or emergency services or services where there is a risk of frequent or severe crisis or involvement with the law."
}

###
POST http://localhost:4000/counselling-services
Content-Type: application/json

{
    "serviceName": "Student test",
    "school": "SFU",
    "location": "Vancouver",
    "organization": "Test",
    "serviceType": [
        "Counselling",
        "Medical"
    ],
    "urgency": "Same Day",
    "targetClients": [
        "SFU students"
    ],
    "isAllDay": false,
    "website": "https://students.ubc.ca/health/ubc-student-assistance-program-sap",
    "specialty": [
        "Stress",
        "Anxiety",
        "Depression",
        "Addiction",
        "Crisis",
        "Grief",
        "Trauma",
        "Fitness",
        "Nutrition",
        "Sleep"
    ],
    "isOfferedOnline": true,
    "delivery": [
        "Online",
        "Phone"
    ],
    "description": "test"
}

###
DELETE http://localhost:4000/counselling-services/62c23ea0246374345e9ded70

###
PATCH http://localhost:4000/counselling-services/6223e2b28bae61f01f2ab573
Content-Type: application/json

{
    "location": "Not Specified"
}