# scratch file with example calls to db apis using VS Code plugin REST Client

GET http://localhost:4000/counselling-services

###
GET http://localhost:4000/counselling-services?isOfferedOnline=true&urgency=Non-urgent

###
GET http://localhost:4000/counselling-services/622b940195fc76787d2782e2

###
POST http://localhost:4000/counselling-services
Content-Type: application/json

{
    "serviceName": "Wellness Together Canada Talk Service",
    "location": "Not Specified",
    "school": "None",
    "organization": "Wellness Together Canada",
    "type": "Phone Counselling",
    "urgency": "Non-urgent",
    "targetClients": [
        "Adults (aged 18+)"
    ],
    "isAllDay": true,
    "website": "https://wellnesstogether.ca/en-CA/service/talk",
    "specialty": [
        "Any Except Crisis"
    ],
    "isOfferedOnline": false,
    "delivery": [
        "Phone"
    ],
    "description": "Our partners provide free support over the phone, to help you through problems big and small. When you call one of the numbers below, you’ll be connected with a professional counsellor who will listen non-judgmentally to whatever’s on your mind."
}
###
DELETE http://localhost:4000/counselling-services/6222ae68c10113e79aea0871

###
PATCH http://localhost:4000/counselling-services/6223e2b28bae61f01f2ab573
Content-Type: application/json

{
    "location": "Not Specified"
}