# scratch file with example calls to db apis using VS Code plugin REST Client

GET http://localhost:4000/counselling-services

###
GET http://localhost:4000/counselling-services?delivery=app

###
GET http://localhost:4000/counselling-services?isOfferedOnline=true&school=UBC

###
GET http://localhost:4000/counselling-services?specialty=anxiety&specialty=stress

###
GET http://localhost:4000/counselling-services/622b940195fc76787d2782e2

###
POST http://localhost:4000/counselling-services
Content-Type: application/json

{
    "serviceName": "Student Assistance Program (SAP)",
    "school": "UBC",
    "organization": "Aspiria",
    "serviceType": [
        "Counselling"
    ],
    "urgency": "Immediate",
    "targetClients": [
        "UBC students"
    ],
    "isAllDay": true,
    "website": "https://students.ubc.ca/health/ubc-student-assistance-program-sap",
    "specialty": [
        "Stress",
        "Anxiety",
        "Depression",
        "Addiction",
        "Crisis",
        "Grief",
        "Trauma",
        "Fitness",
        "Nutrition",
        "Sleep"
    ],
    "isOfferedOnline": true,
    "delivery": [
        "Online",
        "Phone",
        "App"
    ],
    "description": "Offered by Aspiria, the UBC Student Assistance Program (SAP) is a free, 24/7 wellness resource for students. Services include personal counselling, life coaching, group programs and more based on your needs."
}

###
POST http://localhost:4000/counselling-services
Content-Type: application/json

{
    "serviceName": "Student test",
    "school": "SFU",
    "location": "Vancouver",
    "organization": "Test",
    "serviceType": [
        "Counselling",
        "Medical"
    ],
    "urgency": "Same Day",
    "targetClients": [
        "SFU students"
    ],
    "isAllDay": false,
    "website": "https://students.ubc.ca/health/ubc-student-assistance-program-sap",
    "specialty": [
        "Stress",
        "Anxiety",
        "Depression",
        "Addiction",
        "Crisis",
        "Grief",
        "Trauma",
        "Fitness",
        "Nutrition",
        "Sleep"
    ],
    "isOfferedOnline": true,
    "delivery": [
        "Online",
        "Phone"
    ],
    "description": "test"
}

###
DELETE http://localhost:4000/counselling-services/62c23ea0246374345e9ded70

###
PATCH http://localhost:4000/counselling-services/6223e2b28bae61f01f2ab573
Content-Type: application/json

{
    "location": "Not Specified"
}